### ISSUE TITLE
[WOtLK][2.3.1] Sever crashes randomly but no crash logs generated

### ISSUE THREAD

**Issue by flashflash-GIT** [celguar/mangosbot-bots#206]
Hello,

Many thanks for your hard work and for sharing the project. Recently the server (version 2.3.1) started crashing more often. I tried to check Crash logs, but there were only out of date files (for version 2.3.0) in the folder (Server Info -> Crash logs).

The server can start up without any issues, but crashes at random times (approximately 5min - 90min). The previous version 2.3.0 was fairly stable. Actually the version 2.3.1 also worked well for a couple of weeks until this week.

Server Fix seems to be not helpful so far. Would you recommend to wipe and reinstall the DB, or any other fixes? Thank you.

By the way, a very minor issue for Druid Thorns spell. If the spell is recast, the message "A more powerful spell is already active" shows up without resetting the time for the buff.

**Comment by celguar** [comment]
Hello. Please don't use Server Fix, it can't fix crashes. Please switch to Beta build in launcher, it seems to be more stable

**Comment by Fire-Myst** [comment]
Hello all, I think that this is the right place for me to comment. Super new here, and I've been trying to quantify all this wow server stuff.

So I have server crash issues too, been playing around with bot settings, more makes it crash faster. Went through 6 programs before I got to memory leaks and memory dumps, I used DebugDiag Analysis tool to collect and analyze the crashes. What it reported is that there were repeated issues with ntdll.dll and ucrt.dll.

Depending on how many bots run, the crashing occurs somewhere between 3 to 15 minutes, but down to 50 bots the server was running fine for over 2 hours with no crashes. I also tried tweaking some values such as key buffer size, buffer pool size, buffer threads. At maximum levels before crashing, task manager said it was consuming some 6gb of ram with 15 free gigs, and my cpu was running at 4%-8% capacity, and I was advised to install it on an ssd.

I did run sfc /scannow and windows returned no files were corrupted, but I have not updated all my drivers yet to remove those as possible causes of corruption. When I ran Wireshark to monitor tcp packets, world.pkt doesn't actually generate any usable packet crash log, Wireshark appeared to point out the services were self terminating and shutting down the server, presumably due to memory leak and crashing.

I'm attaching the memory dump files, they're screenshots of the .mht files as .mht files are not accepted here. I tried downloading it to pdf but the visual format was screwed up and I'm not actually sure how much more useful all the thread detail would be. But I'll save the logs in case they help out.

![333497158_1371849550217345_4904729631815634083_n](https://user-images.githubusercontent.com/126505261/222025435-efb518ff-594c-4c2c-88e1-8439f6afb5c3.png)
![329092005_697008822174565_7892888621968961498_n](https://user-images.githubusercontent.com/126505261/222025438-05473ce5-f0fd-454c-805d-3bb52660eac7.png)
![333791456_738624714286374_3903334639409020099_n](https://user-images.githubusercontent.com/126505261/222025440-edc9e79f-90fb-4862-a467-46951286c00d.png)
![334006062_178528138237964_6834990705744904735_n](https://user-images.githubusercontent.com/126505261/222025441-b72b5ff4-6dfd-4c69-882b-d86887acbef2.png)
![329425931_527404369462911_7571936679671907896_n(1)](https://user-images.githubusercontent.com/126505261/222025443-f05afd4f-704f-42ae-9ed8-aba4b02f66c7.png)

**Comment by Fire-Myst** [comment]
Hey all, I made a post and deleted it, wasn't sure this was the right place. I followed the classic post, used the installer, downloaded wrath, plays great. Default bot setting of 1k seems to crash within 5 to 15 minutes. Cutting it down to 50 improved stability to at least 2 hours.

I did a ton of stuff to figure out what I can tweak, nothing appeared to solve the issue, eventually debugDiag v2 tools helped, memory trace and memory dumps suggest its ntdll.dll and ucrt.dll that have memory leaks. I'm not really a programmer so I'm not 100% sure this is the answer either, but I took screenshots of the .mht files.

![333497158_1371849550217345_4904729631815634083_n](https://user-images.githubusercontent.com/126505261/222029737-cfec4303-aa80-4f5c-b361-92587c62064b.png)
![329092005_697008822174565_7892888621968961498_n](https://user-images.githubusercontent.com/126505261/222029745-b1a3739c-4fdb-48d1-b567-9d51c1f1b1d2.png)
![333791456_738624714286374_3903334639409020099_n](https://user-images.githubusercontent.com/126505261/222029747-4402a980-8d47-4713-b904-73c2ebf8d1ab.png)
![334006062_178528138237964_6834990705744904735_n](https://user-images.githubusercontent.com/126505261/222029749-e59fdd2b-0859-4099-a9fa-3fbbe1a85a21.png)
![329425931_527404369462911_7571936679671907896_n(1)](https://user-images.githubusercontent.com/126505261/222029751-84c46452-fa47-45b2-b30b-31c27f3a1738.png)

**Comment by celguar** [comment]
Hello please provide crash logs
Launcher -> Server Info -> Crash logs -> .txt files

**Comment by celguar** [comment]
Also make sure you are using latest version of repack (2.3.2)

**Comment by Fire-Myst** [comment]
Wow, thanks for the speedy response! I wish I could provide crash logs but I've checked that specific option several times. Despite my 30 to 50 crashes attempting to tweak configurations, its always stated [no logs]. And believe me, I tried accessing it regardless.

I saw that I am on the 2.3.1 build, tomorrow evening when I get home from work I'll update to 2.3.2.

Again, thanks for the quick reply! I should add I love the concept of thousands of bots on a solo world, a place to play with my friends. It's definitely got me interested in programming and bot/game ai.
